# SORT THE WORDS IN ALPHABETICAL ORDER FROM THE SENTENCE.

# TAKE THE INPUT SENTENCE FROM THE USER .

sentence = input ( "ENTER THE STRINGS :" )
print(sentence)

# BREAK THE COMPLETE SENTENCE INTO SINGLE WORDS .

phrase = sentence.split(" ")
print(phrase)

# SORT THE WORDS IN ASCENDING ORDER .

print ("SORTING THE WORDS FROM THE SENTENCE")
phrase.sort()
print(phrase)

# LOOP THROUGH THE SORTED WORDS .

print ( "THE LIST OF SORTED WORDS" )
for word in phrase:
    print(word)

# EXAMPLE OF SENTENCE : " THE FAMOUS CREATOR OF PYTHON PROGRAMMING LANGUAGE WAS GUIDO VAN ROSSUM AND IT IS AN OPEN SOURCE LANGUAGE " .    